# Generated by Django 5.2.7 on 2025-10-31 02:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecords",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("visit_date", models.DateTimeField()),
                (
                    "chief_complatint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("subjective_note", models.TextField(blank=True, null=True)),
                ("objective_note", models.TextField(blank=True, null=True)),
                ("assessment", models.TextField(blank=True, null=True)),
                ("plan", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "진료 기록",
                "verbose_name_plural": "진료 기록",
                "db_table": "medical_records",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "patient_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "남성"), ("female", "여성")], max_length=6
                    ),
                ),
                (
                    "resident_number",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                ("phone", models.CharField(max_length=11)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "환자",
                "verbose_name_plural": "환자",
                "db_table": "patients",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "announcements_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항",
                "db_table": "announcements",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MedicalDiagnosis",
            fields=[
                ("diagnosis_id", models.AutoField(primary_key=True, serialize=False)),
                ("icd_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "diagnosis_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_primary", models.BooleanField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        db_column="record_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.medicalrecords",
                    ),
                ),
            ],
            options={
                "verbose_name": "진단",
                "verbose_name_plural": "진단",
                "db_table": "medical_diagnosis",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BloodResults",
            fields=[
                ("blood_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ast",
                    models.DecimalField(
                        blank=True,
                        db_column="AST",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "alt",
                    models.DecimalField(
                        blank=True,
                        db_column="ALT",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "alp",
                    models.DecimalField(
                        blank=True,
                        db_column="ALP",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "ggt",
                    models.DecimalField(
                        blank=True,
                        db_column="GGT",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "bilirubin",
                    models.DecimalField(
                        blank=True,
                        db_column="Bilirubin",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "albumin",
                    models.DecimalField(
                        blank=True,
                        db_column="Albumin",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "inr",
                    models.DecimalField(
                        blank=True,
                        db_column="INR",
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "platelet",
                    models.DecimalField(
                        blank=True,
                        db_column="Platelet",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "afp",
                    models.DecimalField(
                        blank=True,
                        db_column="AFP",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        db_column="record_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.medicalrecords",
                    ),
                ),
            ],
            options={
                "verbose_name": "혈액 검사",
                "verbose_name_plural": "혈액 검사",
                "db_table": "blood_results",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MedicalVitals",
            fields=[
                ("vital_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("bp_systolic", models.IntegerField(blank=True, null=True)),
                ("bp_diastolic", models.IntegerField(blank=True, null=True)),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                ("resp_rate", models.IntegerField(blank=True, null=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("oxygen_saturation", models.IntegerField(blank=True, null=True)),
                ("measured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        db_column="record_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.medicalrecords",
                    ),
                ),
            ],
            options={
                "verbose_name": "활력 징후",
                "verbose_name_plural": "활력 징후",
                "db_table": "medical_vitals",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NursingNotes",
            fields=[
                ("note_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "note_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monitoring", "모니터링"),
                            ("intervention", "처치"),
                            ("education", "교육"),
                            ("report", "보고"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("subjective_note", models.TextField(blank=True, null=True)),
                ("objective_note", models.TextField(blank=True, null=True)),
                ("assessment", models.TextField(blank=True, null=True)),
                ("plan", models.TextField(blank=True, null=True)),
                ("intervention", models.TextField(blank=True, null=True)),
                (
                    "abnormal_flag",
                    models.CharField(
                        blank=True,
                        choices=[("normal", "정상"), ("abnormal", "이상")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("next_action", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        db_column="record_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.medicalrecords",
                    ),
                ),
            ],
            options={
                "verbose_name": "간호 기록",
                "verbose_name_plural": "간호 기록",
                "db_table": "nursing_notes",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="medicalrecords",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.patients",
            ),
        ),
        migrations.CreateModel(
            name="DeseaseManage",
            fields=[
                (
                    "desease_manage_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("diagnosis_date", models.DateField(blank=True, null=True)),
                ("bclc_stage", models.CharField(blank=True, max_length=10, null=True)),
                ("tumor_size", models.FloatField(blank=True, null=True)),
                ("tumor_count", models.IntegerField(blank=True, null=True)),
                ("vascular_invasion", models.BooleanField(default=False)),
                ("child_pugh", models.CharField(blank=True, max_length=1, null=True)),
                ("afp_initial", models.FloatField(blank=True, null=True)),
                ("afp_current", models.FloatField(blank=True, null=True)),
                (
                    "treatment_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("treatment_start_date", models.DateField(blank=True, null=True)),
                (
                    "recurrence_risk",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("doctor", models.CharField(blank=True, max_length=10, null=True)),
                ("hospital", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.patients",
                    ),
                ),
            ],
            options={
                "verbose_name": "질병 관리",
                "verbose_name_plural": "질병 관리",
                "db_table": "desease_manage",
                "managed": True,
            },
        ),
    ]
